spring:
  datasource:
    url: jdbc:mysql://localhost:3306/antrigo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta
    username: antrigo
    password: antrigo123
  data:
    redis:
      host: localhost
      port: 6379

app:
  cors:
    allowed-origins: http://localhost:5173
