spring:
  application:
    name: antrigo-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:antrigo}?sslMode=${DB_SSL_MODE:PREFERRED}&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:antrigo123}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Jakarta
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
#  data:
#    redis:
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}
#      password: ${REDIS_PASSWORD:}
#      ssl:
#        enabled: ${REDIS_SSL:false}
#      repositories:
#        enabled: false
#  cache:
#    type: redis
#    redis:
#      time-to-live: 60000
server:
  port: ${PORT:8080}
  error:
    include-message: always
app:
  jwt:
    secret: ${JWT_SECRET:antrigo-super-secret-key-change-in-production-min-256-bits-long}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  cors:
#    allowed-origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000,https://antrigo-aditya-dwi.vercel.app}
    allowed-origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000,}
  queue:
    avg-prep-time-minutes: ${AVG_PREP_MINUTES:4}
  rate-limit:
    checkout-per-minute: ${CHECKOUT_RATE_LIMIT:20}
  qris:
    expiry-minutes: ${QRIS_EXPIRY_MINUTES:15}
    expiry-sweep-ms: ${QRIS_EXPIRY_SWEEP_MS:60000}
midtrans:
  merchant-id: ${MIDTRANS_MERCHANT_ID:}
  client-key: ${MIDTRANS_CLIENT_KEY:}
  server-key: ${MIDTRANS_SERVER_KEY:}
  sandbox: ${MIDTRANS_SANDBOX:}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
logging:
  level:
    com.antrigo: INFO
    org.hibernate.SQL: WARN